<a href="https://colab.research.google.com/github/hye0-n0/KRX_stock_prediction/blob/main/%5B0704%5DArima_baseline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import random
import os
from tqdm import tqdm
from statsmodels.tsa.arima.model import ARIMA

import warnings
warnings.filterwarnings("ignore")

In [ ]:
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)

seed_everything(42) # Seed 고정

## DataLoad

공유드라이브는 mounting이 힘들기 때문에 </br>공유함에 있는 데이터 파일 open의 shortcut을 nyDrive에 만들면 됩니다

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/open/train.csv')
train

              일자     종목코드     종목명      거래량     시가     고가     저가     종가
0       20210601  A060310      3S   166690   2890   2970   2885   2920
1       20210601  A095570  AJ네트웍스    63836   5860   5940   5750   5780
2       20210601  A006840   AK홀딩스   103691  35500  35600  34150  34400
3       20210601  A054620     APS   462544  14600  14950  13800  14950
4       20210601  A265520   AP시스템   131987  29150  29150  28800  29050
...          ...      ...     ...      ...    ...    ...    ...    ...
987995  20230530  A189980  흥국에프엔비   272284   3005   3035   2955   2980
987996  20230530  A000540    흥국화재    50218   3250   3255   3195   3215
987997  20230530  A003280    흥아해운   130664   1344   1395   1340   1370
987998  20230530  A037440      희림   141932   9170   9260   9170   9200
987999  20230530  A238490      힘스  2611843   6410   8220   6300   8220

[988000 rows x 8 columns]

##Model Define, Train and Inference

arima 모델은 순차적 계산으로 gpu의 성능차이가 거의 없음

In [ ]:
# 추론 결과를 저장하기 위한 dataframe 생성
results_df = pd.DataFrame(columns=['종목코드', 'final_return'])

# train 데이터에 존재하는 독립적인 종목코드 추출
unique_codes = train['종목코드'].unique()

# 각 종목코드에 대해서 모델 학습 및 추론 반복
for code in tqdm(unique_codes):

    # 학습 데이터 생성
    train_close = train[train['종목코드'] == code][['일자', '종가']]
    train_close['일자'] = pd.to_datetime(train_close['일자'], format='%Y%m%d')
    train_close.set_index('일자', inplace=True)
    tc = train_close['종가']

    # 모델 선언, 학습 및 추론
    model = ARIMA(tc, order=(2, 1, 2))
    model_fit = model.fit()
    predictions = model_fit.forecast(steps=15) # 향후 15개의 거래일에 대해서 예측

    # 최종 수익률 계산
    final_return = (predictions.iloc[-1] - predictions.iloc[0]) / predictions.iloc[0]

    # 결과 저장
    results_df = results_df.append({'종목코드': code, 'final_return': final_return}, ignore_index=True)

100%|██████████| 2000/2000 [25:40<00:00,  1.30it/s]

In [ ]:
results_df['순위'] = results_df['final_return'].rank(method='first', ascending=False).astype('int') # 각 순위를 중복없이 생성
results_df

         종목코드  final_return    순위
0     A060310     -0.056272  1991
1     A095570     -0.002833  1679
2     A006840      0.003040   354
3     A054620      0.001876   488
4     A265520      0.002090   452
...       ...           ...   ...
1995  A189980      0.000630   730
1996  A000540      0.002514   400
1997  A003280      0.001430   553
1998  A037440      0.002921   363
1999  A238490      0.010894   115

[2000 rows x 3 columns]

## Submit

In [ ]:
sample_submission = pd.read_csv('/content/drive/MyDrive/open/sample_submission.csv')
sample_submission

         종목코드    순위
0     A000020     1
1     A000040     2
2     A000050     3
3     A000070     4
4     A000080     5
...       ...   ...
1995  A375500  1996
1996  A378850  1997
1997  A383220  1998
1998  A383310  1999
1999  A383800  2000

[2000 rows x 2 columns]

In [ ]:
baseline_submission = sample_submission[['종목코드']].merge(results_df[['종목코드', '순위']], on='종목코드', how='left')
baseline_submission

         종목코드    순위
0     A000020   501
1     A000040  1653
2     A000050   866
3     A000070  1077
4     A000080  1204
...       ...   ...
1995  A375500   753
1996  A378850   558
1997  A383220   620
1998  A383310   244
1999  A383800  1085

[2000 rows x 2 columns]

In [ ]:
baseline_submission.to_csv('Arima_submission.csv', index=False)